### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by ebelizm** [akasakaid/pricktod#2]
[2024-06-03 15:18:25] account number : 2
[2024-06-03 15:18:27] connect to wss server !
Traceback (most recent call last):
  File "D:\scspam\pricktod\bot.py", line 203, in <module>
    app.main()
  File "D:\scspam\pricktod\bot.py", line 184, in main
    self.game(id)
  File "D:\scspam\pricktod\bot.py", line 95, in game
    open(".wss_logs.log", "a").write(res + "\n")
  File "C:\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u039e' in position 126: character maps to <undefined>

**Comment by akasakaid** [comment]
Oke bang, gw fix dolo

**Comment by akasakaid** [comment]
Oke, udah gw update bang bisa di `git pull`

**Comment by ebelizm** [comment]
fixed.
btw suka aktif di group mana kas?

**Comment by akasakaid** [comment]
gw mah dimana mana aja sih bang, join sana join sini wkwkkkwk. Ini aja gw bikin grup buat orang yang tanya bot yang gw bikin wwk

**Comment by ebelizm** [comment]
siapa tau bikin group sendiri

**Comment by akasakaid** [comment]
Ya ada sih bang ini [@sdsproject_chat](https://t.me/sdsproject_chat) buat orang tanya tanya bot yang gw bikin. kalo gw bikin bot sih gw share juga disana wkwkwwk

**Comment by ebelizm** [comment]
raise WebSocketConnectionClosedException("Connection to remote host was lost.")
websocket._exceptions.WebSocketConnectionClosedException: Connection to remote host was lost.

**Comment by akasakaid** [comment]
Oke ntar gw tambahin handling error buat itu

**Comment by baztardengine** [comment]
raise WebSocketConnectionClosedException("Connection to remote host was lost.")

masih sering bgtu om

**Comment by akasakaid** [comment]
Barusan saya update, bisa dicoba updatenya
