### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by unh4cked** [akasakaid/pricktod#3]
Traceback (most recent call last):
  File "/home/unhckedc/files/adrop/prick/prick.py", line 221, in <module>
    app.main()
  File "/home/unhckedc/files/adrop/prick/prick.py", line 202, in main
    self.game(id)
  File "/home/unhckedc/files/adrop/prick/prick.py", line 132, in game
    free_turbo, end_turbo = self.active_turbo(id, user_agent)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unhckedc/files/adrop/prick/prick.py", line 66, in active_turbo
    end_free_turbo = res.json()["result"]["turboEndedAt"].replace("Z", "")
                     ~~~~~~~~~~^^^^^^^^^^
KeyError: 'result'

**Comment by akasakaid** [comment]
> Traceback (most recent call last):
>   File "/home/unhckedc/files/adrop/prick/prick.py", line 221, in <module>
>     app.main()
>   File "/home/unhckedc/files/adrop/prick/prick.py", line 202, in main
>     self.game(id)
>   File "/home/unhckedc/files/adrop/prick/prick.py", line 132, in game
>     free_turbo, end_turbo = self.active_turbo(id, user_agent)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/unhckedc/files/adrop/prick/prick.py", line 66, in active_turbo
>     end_free_turbo = res.json()["result"]["turboEndedAt"].replace("Z", "")
>                      ~~~~~~~~~~^^^^^^^^^^
> KeyError: 'result'
> 

Maybe you can try another script bot

**Comment by tuanteku9x** [comment]
Yes not working
